name: Update Kubernetes OpenAPI
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python updater/fetch_openapi.py
      - run: python ingest/indexer.py
      - name: Commit updates
        run: |
          git config user.name "k8s-agent-bot"
          git config user.email "bot@aavams.ai"
          git add data/
          git commit -m "Auto-update OpenAPI index" || echo "No changes"
          git push
